//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatitasV01.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDD_PATITASEntitiesGeneral : DbContext
    {
        public BDD_PATITASEntitiesGeneral()
            : base("name=BDD_PATITASEntitiesGeneral")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<tbl_cabeceraHClinica> tbl_cabeceraHClinica { get; set; }
        public DbSet<tbl_cita> tbl_cita { get; set; }
        public DbSet<tbl_detalleCita> tbl_detalleCita { get; set; }
        public DbSet<tbl_detalleVenta> tbl_detalleVenta { get; set; }
        public DbSet<tbl_historiaClinica> tbl_historiaClinica { get; set; }
        public DbSet<tbl_mascota> tbl_mascota { get; set; }
        public DbSet<tbl_servicio> tbl_servicio { get; set; }
        public DbSet<tbl_tiposMascota> tbl_tiposMascota { get; set; }
        public DbSet<tbl_usuario> tbl_usuario { get; set; }
        public DbSet<tbl_venta> tbl_venta { get; set; }
    }
}
