//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatitasV01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_servicio
    {
        public tbl_servicio()
        {
            this.tbl_detalleCita = new HashSet<tbl_detalleCita>();
            this.tbl_detalleVenta = new HashSet<tbl_detalleVenta>();
            this.tbl_historiaClinica = new HashSet<tbl_historiaClinica>();
        }
    
        public int ser_codigo { get; set; }
        public string ser_nombre { get; set; }
        public double ser_precio { get; set; }
        public string ser_descripcion { get; set; }
        public double ser_iva { get; set; }
    
        public virtual ICollection<tbl_detalleCita> tbl_detalleCita { get; set; }
        public virtual ICollection<tbl_detalleVenta> tbl_detalleVenta { get; set; }
        public virtual ICollection<tbl_historiaClinica> tbl_historiaClinica { get; set; }
    }
}
