//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatitasV01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_tiposMascota
    {
        public tbl_tiposMascota()
        {
            this.tbl_mascota = new HashSet<tbl_mascota>();
        }
    
        public int tim_codigo { get; set; }
        public string tim_nombre { get; set; }
        public string tim_descripcion { get; set; }
    
        public virtual ICollection<tbl_mascota> tbl_mascota { get; set; }
    }
}
