//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatitasV01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_mascota
    {
        public tbl_mascota()
        {
            this.tbl_cabeceraHClinica = new HashSet<tbl_cabeceraHClinica>();
        }
    
        public int mas_codigo { get; set; }
        public string mas_nombre { get; set; }
        public string mas_fecha_nac { get; set; }
        public string mas_raza { get; set; }
        public int tim_codigo { get; set; }
        public string mas_sexo { get; set; }
    
        public virtual ICollection<tbl_cabeceraHClinica> tbl_cabeceraHClinica { get; set; }
        public virtual tbl_tiposMascota tbl_tiposMascota { get; set; }
    }
}
