//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatitasV01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_detalleVenta
    {
        public int dev_codigo { get; set; }
        public int dev_cantidad { get; set; }
        public int ser_codigo { get; set; }
        public string dev_descripcion { get; set; }
        public int ven_codigo { get; set; }
    
        public virtual tbl_servicio tbl_servicio { get; set; }
        public virtual tbl_venta tbl_venta { get; set; }
    }
}
