//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatitasV01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_cabeceraHClinica
    {
        public tbl_cabeceraHClinica()
        {
            this.tbl_historiaClinica = new HashSet<tbl_historiaClinica>();
        }
    
        public int chc_codigo { get; set; }
        public string chc_fecha { get; set; }
        public int mas_codigo { get; set; }
        public int usu_codigo { get; set; }
    
        public virtual tbl_mascota tbl_mascota { get; set; }
        public virtual tbl_usuario tbl_usuario { get; set; }
        public virtual ICollection<tbl_historiaClinica> tbl_historiaClinica { get; set; }
    }
}
