//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatitasV01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_detalleCita
    {
        public int dci_codigo { get; set; }
        public int cit_codigo { get; set; }
        public string dci_descripcion { get; set; }
        public int ser_codigo { get; set; }
    
        public virtual tbl_cita tbl_cita { get; set; }
        public virtual tbl_servicio tbl_servicio { get; set; }
    }
}
