//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatitasV01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_venta
    {
        public tbl_venta()
        {
            this.tbl_detalleVenta = new HashSet<tbl_detalleVenta>();
        }
    
        public int ven_codigo { get; set; }
        public string ven_fecha { get; set; }
        public int usu_codigo { get; set; }
        public double ven_subtotal { get; set; }
        public double ven_total { get; set; }
    
        public virtual ICollection<tbl_detalleVenta> tbl_detalleVenta { get; set; }
        public virtual tbl_usuario tbl_usuario { get; set; }
    }
}
