//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatitasV01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_usuario
    {
        public tbl_usuario()
        {
            this.tbl_cabeceraHClinica = new HashSet<tbl_cabeceraHClinica>();
            this.tbl_venta = new HashSet<tbl_venta>();
        }
    
        public int usu_codigo { get; set; }
        public string usu_nombres { get; set; }
        public string usu_apellidos { get; set; }
        public string usu_correo { get; set; }
        public string usu_telefono { get; set; }
        public string usu_cedula { get; set; }
        public string usu_tipo { get; set; }
        public string usu_pass { get; set; }
        public string usu_direccion { get; set; }
    
        public virtual ICollection<tbl_cabeceraHClinica> tbl_cabeceraHClinica { get; set; }
        public virtual ICollection<tbl_venta> tbl_venta { get; set; }
    }
}
