//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatitasV01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_cita
    {
        public tbl_cita()
        {
            this.tbl_detalleCita = new HashSet<tbl_detalleCita>();
        }
    
        public int cit_codigo { get; set; }
        public string cit_fecha { get; set; }
        public string cit_hora { get; set; }
        public string cit_descripcion { get; set; }
        public int usu_codigo { get; set; }
    
        public virtual ICollection<tbl_detalleCita> tbl_detalleCita { get; set; }
    }
}
